# Generated by Django 3.1.6 on 2021-03-31 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=280)),
                ('thought', models.TextField()),
                ('music', models.TextField()),
                ('link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dev_blog_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_post', models.CharField(max_length=999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_comments', to='dev_blog_app.entry')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='dev_blog_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.CharField(max_length=255)),
                ('platforms', models.CharField(max_length=255)),
                ('resources', models.CharField(max_length=255)),
                ('code_book', models.CharField(max_length=255)),
                ('book', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='dev_blog_app.user')),
            ],
        ),
    ]
